### ISSUE TITLE
Are Pose keypoints independent of pose classification?

### ISSUE THREAD

**Issue by gsandy9** [satyaborg/pose-estimation-detection#4]
Hello,

While looking through your code I got to know that you have used keypoints only to detect the skeleton and custom images trained using pretrained model to detect the poses. 

You are not using the poses keypoints from open pose to classify the pose. Am I thinking right?

**Comment by satyaborg** [comment]
Yes, that is correct @gsandy9 
One can use a secondary dense layer that is jointly trained with the raw pose keypoints (coordinates). However, using only the images proved to be effective for a first pass.
